Class {
	#name : #AlceNorthwindFormBindingTest,
	#superclass : #AlceNorthwindCachedModelAbstractTest,
	#category : #'Alce-Test-Bind'
}

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormInventoryListcmdPurchase_Click [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Inventory List').
	(#fixture -> {
	(#functionOrSub -> #cmdPurchase_Click).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormOrderDetailsClearShippingAddress [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Order Details').
	(#fixture -> {
	(#functionOrSub -> #ClearShippingAddress).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormOrderDetailsCustomer_ID_AfterUpdate [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Order Details').
	(#fixture -> {
	(#functionOrSub -> #Customer_ID_AfterUpdate).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormOrderDetailsForm_Current [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Order Details').
	(#fixture -> {
	(#functionOrSub -> #Form_Current).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormOrderDetailsForm_Load [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Order Details').
	(#fixture -> {
	(#functionOrSub -> #Form_Load).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormOrderDetailsGetDefaultSalesPersonID [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Order Details').
	(#fixture -> {
	(#functionOrSub -> #GetDefaultSalesPersonID).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormOrderDetailsSetDefaultShippingAddress [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Order Details').
	(#fixture -> {
	(#functionOrSub -> #SetDefaultShippingAddress).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormOrderDetailsSetFormState [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Order Details').
	(#fixture -> {
	(#functionOrSub -> #SetFormState).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormOrderDetailsValidateOrder [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Order Details').
	(#fixture -> {
	(#functionOrSub -> #ValidateOrder).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormOrderDetailsValidatePaymentInfo [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Order Details').
	(#fixture -> {
	(#functionOrSub -> #ValidatePaymentInfo).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormOrderDetailsValidateShipping [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Order Details').
	(#fixture -> {
	(#functionOrSub -> #ValidateShipping).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormOrderDetailscmdClearAddress_Click [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Order Details').
	(#fixture -> {
	(#functionOrSub -> #cmdClearAddress_Click).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormOrderDetailscmdCompleteOrder_Click [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Order Details').
	(#fixture -> {
	(#functionOrSub -> #cmdCompleteOrder_Click).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormOrderDetailscmdCreateInvoice_Click [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Order Details').
	(#fixture -> {
	(#functionOrSub -> #cmdCreateInvoice_Click).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormOrderDetailscmdDeleteOrder_Click [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Order Details').
	(#fixture -> {
	(#functionOrSub -> #cmdDeleteOrder_Click).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormOrderDetailscmdShipOrder_Click [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Order Details').
	(#fixture -> {
	(#functionOrSub -> #cmdShipOrder_Click).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormOrderSubformforOrderDetailsForm_Current [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Order Subform for Order Details').
	(#fixture -> {
	(#functionOrSub -> #Form_Current).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormOrderSubformforOrderDetailsProduct_ID_AfterUpdate [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Order Subform for Order Details').
	(#fixture -> {
	(#functionOrSub -> #Product_ID_AfterUpdate).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormOrderSubformforOrderDetailsQuantity_AfterUpdate [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Order Subform for Order Details').
	(#fixture -> {
	(#functionOrSub -> #Quantity_AfterUpdate).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormOrderSubformforOrderDetailsStatus_Name_DblClick [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Order Subform for Order Details').
	(#fixture -> {
	(#functionOrSub -> #Status_Name_DblClick).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormPurchaseOrderDetailsFRemovePurchaseLineItems [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Purchase Order Details').
	(#fixture -> {
	(#functionOrSub -> #FRemovePurchaseLineItems).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormPurchaseOrderDetailsForm_Current [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Purchase Order Details').
	(#fixture -> {
	(#functionOrSub -> #Form_Current).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormPurchaseOrderDetailsGetPurchaseDetailsSubform [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Purchase Order Details').
	(#fixture -> {
	(#functionOrSub -> #GetPurchaseDetailsSubform).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormPurchaseOrderDetailsInitFormState [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Purchase Order Details').
	(#fixture -> {
	(#functionOrSub -> #InitFormState).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormPurchaseOrderDetailsPurchaseContainsLineItems [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Purchase Order Details').
	(#fixture -> {
	(#functionOrSub -> #PurchaseContainsLineItems).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormPurchaseOrderDetailsPurchaseOrderIsValid [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Purchase Order Details').
	(#fixture -> {
	(#functionOrSub -> #PurchaseOrderIsValid).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormPurchaseOrderDetailsPurchaseOrder_ContainsPostedInventory [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Purchase Order Details').
	(#fixture -> {
	(#functionOrSub -> #PurchaseOrder_ContainsPostedInventory).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormPurchaseOrderDetailsSupplier_ID_AfterUpdate [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Purchase Order Details').
	(#fixture -> {
	(#functionOrSub -> #Supplier_ID_AfterUpdate).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormPurchaseOrderDetailsSupplier_ID_BeforeUpdate [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Purchase Order Details').
	(#fixture -> {
	(#functionOrSub -> #Supplier_ID_BeforeUpdate).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormPurchaseOrderDetailsTabCtlPurchasing_Change [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Purchase Order Details').
	(#fixture -> {
	(#functionOrSub -> #TabCtlPurchasing_Change).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormPurchaseOrderDetailscmdApprovePurchase_Click [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Purchase Order Details').
	(#fixture -> {
	(#functionOrSub -> #cmdApprovePurchase_Click).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormPurchaseOrderDetailscmdCancelPurchase_Click [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Purchase Order Details').
	(#fixture -> {
	(#functionOrSub -> #cmdCancelPurchase_Click).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormPurchaseOrderDetailscmdClose_Click [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Purchase Order Details').
	(#fixture -> {
	(#functionOrSub -> #cmdClose_Click).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormPurchaseOrderDetailscmdSubmitforApproval_Click [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Purchase Order Details').
	(#fixture -> {
	(#functionOrSub -> #cmdSubmitforApproval_Click).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormPurchasesSubformforPurchaseOrderDetailsForm_AfterInsert [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Purchases Subform for Purchase Order Details').
	(#fixture -> {
	(#functionOrSub -> #Form_AfterInsert).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormPurchasesSubformforPurchaseOrderDetailsForm_BeforeUpdate [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Purchases Subform for Purchase Order Details').
	(#fixture -> {
	(#functionOrSub -> #Form_BeforeUpdate).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormPurchasesSubformforPurchaseOrderDetailsInitParentState [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Purchases Subform for Purchase Order Details').
	(#fixture -> {
	(#functionOrSub -> #InitParentState).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormPurchasesSubformforPurchaseOrderDetailsProduct_ID_AfterUpdate [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Purchases Subform for Purchase Order Details').
	(#fixture -> {
	(#functionOrSub -> #Product_ID_AfterUpdate).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormPurchasesSubformforPurchaseOrderDetailsQuantity_AfterUpdate [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Purchases Subform for Purchase Order Details').
	(#fixture -> {
	(#functionOrSub -> #Quantity_AfterUpdate).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormPurchasesSubformforPurchaseOrderDetailsQuantity_BeforeUpdate [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Purchases Subform for Purchase Order Details').
	(#fixture -> {
	(#functionOrSub -> #Quantity_BeforeUpdate).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormPurchasesSubformforPurchaseOrderDetailsRemoveCurrentLineItem [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Purchases Subform for Purchase Order Details').
	(#fixture -> {
	(#functionOrSub -> #RemoveCurrentLineItem).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormPurchasesSubformforPurchaseOrderDetailsUnit_Cost_BeforeUpdate [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Purchases Subform for Purchase Order Details').
	(#fixture -> {
	(#functionOrSub -> #Unit_Cost_BeforeUpdate).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormReceivingSubformforPurchaseOrderDetailsDate_Received_AfterUpdate [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Receiving Subform for Purchase Order Details').
	(#fixture -> {
	(#functionOrSub -> #Date_Received_AfterUpdate).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormReceivingSubformforPurchaseOrderDetailsForm_Current [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Receiving Subform for Purchase Order Details').
	(#fixture -> {
	(#functionOrSub -> #Form_Current).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormReceivingSubformforPurchaseOrderDetailsForm_Load [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Receiving Subform for Purchase Order Details').
	(#fixture -> {
	(#functionOrSub -> #Form_Load).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormReceivingSubformforPurchaseOrderDetailsPosted_To_Inventory_AfterUpdate [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Receiving Subform for Purchase Order Details').
	(#fixture -> {
	(#functionOrSub -> #Posted_To_Inventory_AfterUpdate).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormSalesReportsDialogForm_Load [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Sales Reports Dialog').
	(#fixture -> {
	(#functionOrSub -> #Form_Load).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormSalesReportsDialogGetLastOrderDate [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Sales Reports Dialog').
	(#fixture -> {
	(#functionOrSub -> #GetLastOrderDate).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormSalesReportsDialogInitFilterItems [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Sales Reports Dialog').
	(#fixture -> {
	(#functionOrSub -> #InitFilterItems).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormSalesReportsDialogPrintReports [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Sales Reports Dialog').
	(#fixture -> {
	(#functionOrSub -> #PrintReports).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormSalesReportsDialogSetSalesPeriod [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Sales Reports Dialog').
	(#fixture -> {
	(#functionOrSub -> #SetSalesPeriod).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormSalesReportsDialogcmdPreview_Click [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Sales Reports Dialog').
	(#fixture -> {
	(#functionOrSub -> #cmdPreview_Click).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormSalesReportsDialogcmdPrint_Click [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Sales Reports Dialog').
	(#fixture -> {
	(#functionOrSub -> #cmdPrint_Click).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormSalesReportsDialoglstSalesPeriod_AfterUpdate [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Sales Reports Dialog').
	(#fixture -> {
	(#functionOrSub -> #lstSalesPeriod_AfterUpdate).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> setupAlcixFormSalesReportsDialoglstSalesReports_AfterUpdate [
	^ {(#kind -> AlcixForm).
	(#nameOfFSTCitizen -> #'Sales Reports Dialog').
	(#fixture -> {
	(#functionOrSub -> #lstSalesReports_AfterUpdate).
	(#accessBoundAttributes -> 0) .
	(#returnTypeBindingExpected -> true) .
	(#variableTypesBound -> 0) .
	(#variableBound -> 0) .
	(#expectedIncomingBound -> 0) .
	(#expectedOutgoingBound -> 0) 
	})}
]

{ #category : #'as yet unclassified' }
AlceNorthwindFormBindingTest class >> testParameters [
	^ super testParameters
		addCase: self setupAlcixFormOrderDetailsGetDefaultSalesPersonID;
		addCase: self setupAlcixFormOrderDetailscmdCreateInvoice_Click;
		addCase: self setupAlcixFormPurchaseOrderDetailsForm_Current;
		addCase:
			self
				setupAlcixFormPurchasesSubformforPurchaseOrderDetailsForm_AfterInsert;
		addCase: self setupAlcixFormOrderDetailsClearShippingAddress;
		addCase: self setupAlcixFormPurchaseOrderDetailsPurchaseOrderIsValid;
		addCase: self setupAlcixFormOrderDetailsCustomer_ID_AfterUpdate;
		addCase: self setupAlcixFormPurchaseOrderDetailsSupplier_ID_BeforeUpdate;
		addCase:
			self
				setupAlcixFormPurchasesSubformforPurchaseOrderDetailsQuantity_AfterUpdate;
		addCase: self setupAlcixFormOrderDetailsSetFormState;
		addCase: self setupAlcixFormOrderDetailscmdDeleteOrder_Click;
		addCase: self setupAlcixFormPurchaseOrderDetailscmdSubmitforApproval_Click;
		addCase: self setupAlcixFormOrderDetailscmdCompleteOrder_Click;
		addCase: self setupAlcixFormSalesReportsDialogInitFilterItems;
		addCase: self setupAlcixFormPurchaseOrderDetailsSupplier_ID_AfterUpdate;
		addCase: self setupAlcixFormSalesReportsDialogPrintReports;
		addCase: self setupAlcixFormOrderDetailsForm_Load;
		addCase: self setupAlcixFormOrderDetailsValidatePaymentInfo;
		addCase: self setupAlcixFormPurchaseOrderDetailsGetPurchaseDetailsSubform;
		addCase:
			self
				setupAlcixFormPurchasesSubformforPurchaseOrderDetailsUnit_Cost_BeforeUpdate;
		addCase:
			self
				setupAlcixFormPurchasesSubformforPurchaseOrderDetailsProduct_ID_AfterUpdate;
		addCase: self setupAlcixFormSalesReportsDialoglstSalesReports_AfterUpdate;
		addCase: self setupAlcixFormOrderDetailscmdClearAddress_Click;
		addCase:
			self
				setupAlcixFormPurchasesSubformforPurchaseOrderDetailsInitParentState;
		addCase: self setupAlcixFormPurchaseOrderDetailscmdApprovePurchase_Click;
		addCase: self setupAlcixFormPurchaseOrderDetailsPurchaseContainsLineItems;
		addCase: self setupAlcixFormOrderDetailsSetDefaultShippingAddress;
		addCase:
			self
				setupAlcixFormPurchasesSubformforPurchaseOrderDetailsRemoveCurrentLineItem;
		addCase: self setupAlcixFormPurchaseOrderDetailsFRemovePurchaseLineItems;
		addCase: self setupAlcixFormReceivingSubformforPurchaseOrderDetailsForm_Current;
		addCase: self setupAlcixFormPurchaseOrderDetailsTabCtlPurchasing_Change;
		addCase: self setupAlcixFormOrderDetailsForm_Current;
		addCase: self setupAlcixFormOrderDetailsValidateOrder;
		addCase: self setupAlcixFormReceivingSubformforPurchaseOrderDetailsForm_Load;
		addCase: self setupAlcixFormOrderSubformforOrderDetailsStatus_Name_DblClick;
		addCase:
			self
				setupAlcixFormReceivingSubformforPurchaseOrderDetailsDate_Received_AfterUpdate;
		addCase: self setupAlcixFormInventoryListcmdPurchase_Click;
		addCase: self setupAlcixFormPurchaseOrderDetailscmdClose_Click;
		addCase: self setupAlcixFormOrderSubformforOrderDetailsQuantity_AfterUpdate;
		addCase: self setupAlcixFormOrderDetailsValidateShipping;
		addCase: self setupAlcixFormSalesReportsDialogcmdPreview_Click;
		addCase: self setupAlcixFormPurchaseOrderDetailscmdCancelPurchase_Click;
		addCase:
			self
				setupAlcixFormPurchaseOrderDetailsPurchaseOrder_ContainsPostedInventory;
		addCase: self setupAlcixFormSalesReportsDialogForm_Load;
		addCase:
			self
				setupAlcixFormReceivingSubformforPurchaseOrderDetailsPosted_To_Inventory_AfterUpdate;
		addCase: self setupAlcixFormOrderSubformforOrderDetailsForm_Current;
		addCase: self setupAlcixFormSalesReportsDialogcmdPrint_Click;
		addCase: self setupAlcixFormOrderSubformforOrderDetailsProduct_ID_AfterUpdate;
		addCase:
			self
				setupAlcixFormPurchasesSubformforPurchaseOrderDetailsForm_BeforeUpdate;
		addCase: self setupAlcixFormPurchaseOrderDetailsInitFormState;
		addCase:
			self
				setupAlcixFormPurchasesSubformforPurchaseOrderDetailsQuantity_BeforeUpdate;
		addCase: self setupAlcixFormSalesReportsDialogSetSalesPeriod;
		addCase: self setupAlcixFormSalesReportsDialogGetLastOrderDate;
		addCase: self setupAlcixFormOrderDetailscmdShipOrder_Click;
		addCase: self setupAlcixFormSalesReportsDialoglstSalesPeriod_AfterUpdate
]

{ #category : #tests }
AlceNorthwindFormBindingTest >> testAccessesAreBoundProperly [
	self
		assert: (self functionOrSub accesses select: [ :s | s attribute isNotNil ]) size
		equals: (fixture at: #accessBoundAttributes)
]

{ #category : #tests }
AlceNorthwindFormBindingTest >> testBoundedReturnType [
	self functionOrSub class = AlcixSubProcedure
		ifTrue: [ ^ self skip ].
	self
		assert: self functionOrSub type isNotNil
		equals: (fixture at: #returnTypeBindingExpected)
]

{ #category : #tests }
AlceNorthwindFormBindingTest >> testBoundedVariableTypes [
	self
		assert:
			(self functionOrSub localVariables select: [ :s | s type isNotNil ])
				size
		equals: (fixture at: #variableTypesBound)
]

{ #category : #tests }
AlceNorthwindFormBindingTest >> testBoundedVariables [
	self
		assert: (self functionOrSub localVariables select: [ :s | s access isEmptyOrNil not ]) size
		equals: (fixture at: #variableBound)
]

{ #category : #tests }
AlceNorthwindFormBindingTest >> testIncomingCallsAreBoundProperly [
	self
		assert: self functionOrSub incomingInvocations size
		equals: (fixture at: #expectedIncomingBound)
]

{ #category : #tests }
AlceNorthwindFormBindingTest >> testOutgoingCallsAreBoundProperly [
	self
		assert: (self functionOrSub outgoingInvocations select: [ :s | s candidate isNotNil ]) size
		equals: (fixture at: #expectedOutgoingBound) 
]
